services:            
    anomalies.twig_extension:
        class: AnomaliesBundle\Twig\AnomaliesdecodeExtension
        public: false
        tags:
            - { name: twig.extension }
            
    application.file_uploader:
        class: AnomaliesBundle\Services\FileUploader
#        arguments: ['%path%']
        arguments: []