services:            
    anomalies.twig_extension:
        class: AnomaliesBundle\Twig\AnomaliesdecodeExtension
        public: false
        tags:
            - { name: twig.extension }
            
    application.file_uploader:
        class: AnomaliesBundle\Services\FileUploader
        arguments: ['@request_stack', '@doctrine.orm.entity_manager','@session', '@router','anomaliesdecode', 'roleuser_edit','anomaliesbundle_documents','userfile','description','%kernel.root_dir%']
#        arguments: []