anomalies_risklevel:
    resource: "@AnomaliesBundle/Resources/config/routing/risklevel.yml"
    prefix:   /risklevel

anomalies_homepage:
    path:     /hello/{name}
    defaults: { _controller: AnomaliesBundle:Default:index }
