anomalies_controles:
    resource: "@AnomaliesBundle/Resources/config/routing/controles.yml"
    prefix:   /controles

anomalies_typecontrole:
    resource: "@AnomaliesBundle/Resources/config/routing/typecontrole.yml"
    prefix:   /typecontrole

anomalies_typesociete:
    resource: "@AnomaliesBundle/Resources/config/routing/typesociete.yml"
    prefix:   /typesociete

anomalies_typetaches:
    resource: "@AnomaliesBundle/Resources/config/routing/typetaches.yml"
    prefix:   /typetaches

anomalies_risklevel:
    resource: "@AnomaliesBundle/Resources/config/routing/risklevel.yml"
    prefix:   /risklevel

anomalies_homepage:
    path:     /hello/{name}
    defaults: { _controller: AnomaliesBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: AnomaliesBundle:Login:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
