anomalies:
    resource: "@AnomaliesBundle/Resources/config/routing.yml"
    prefix:   /anomalies

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


