typetaches:
    path:     /
    defaults: { _controller: "AnomaliesBundle:Typetaches:index" }

typetaches_new:
    path:     /new
    defaults: { _controller: "AnomaliesBundle:Typetaches:new" }

typetaches_create:
    path:     /create
    defaults: { _controller: "AnomaliesBundle:Typetaches:create" }
    methods:  [POST, PUT, GET]

typetaches_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnomaliesBundle:Typetaches:edit" }

typetaches_update:
    path:     /{id}/update
    defaults: { _controller: "AnomaliesBundle:Typetaches:update" }
    methods:  [POST, PUT, GET]

typetaches_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnomaliesBundle:Typetaches:delete" }
    methods:  [POST,GET, DELETE]
