typesociete:
    path:     /
    defaults: { _controller: "AnomaliesBundle:Typesociete:index" }

typesociete_show:
    path:     /{id}/show
    defaults: { _controller: "AnomaliesBundle:Typesociete:show" }

typesociete_new:
    path:     /new
    defaults: { _controller: "AnomaliesBundle:Typesociete:new" }

typesociete_create:
    path:     /create
    defaults: { _controller: "AnomaliesBundle:Typesociete:create" }
    methods:  POST

typesociete_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnomaliesBundle:Typesociete:edit" }

typesociete_update:
    path:     /{id}/update
    defaults: { _controller: "AnomaliesBundle:Typesociete:update" }
    methods:  [POST, PUT]

typesociete_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnomaliesBundle:Typesociete:delete" }
    methods:  [POST, DELETE]
