typecontrole:
    path:     /
    defaults: { _controller: "AnomaliesBundle:Typecontrole:index" }

typecontrole_new:
    path:     /new
    defaults: { _controller: "AnomaliesBundle:Typecontrole:new" }

typecontrole_create:
    path:     /create
    defaults: { _controller: "AnomaliesBundle:Typecontrole:create" }
    methods:  [POST, PUT, GET]

typecontrole_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnomaliesBundle:Typecontrole:edit" }

typecontrole_update:
    path:     /{id}/update
    defaults: { _controller: "AnomaliesBundle:Typecontrole:update" }
    methods:  [POST, PUT, GET]

typecontrole_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnomaliesBundle:Typecontrole:delete" }

