typesociete:
    path:     /
    defaults: { _controller: "AnomaliesBundle:Typesociete:index" }

typesociete_new:
    path:     /new
    defaults: { _controller: "AnomaliesBundle:Typesociete:new" }

typesociete_create:
    path:     /create
    defaults: { _controller: "AnomaliesBundle:Typesociete:create" }
    methods:  [POST, PUT, GET]

typesociete_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnomaliesBundle:Typesociete:edit" }

typesociete_update:
    path:     /{id}/update
    defaults: { _controller: "AnomaliesBundle:Typesociete:update" }
    methods:  [POST, PUT, GET]

typesociete_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnomaliesBundle:Typesociete:delete" }
    methods:  [POST,GET, DELETE]
