<?php

namespace AnomaliesBundle\Entity;

/**
 * ControlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlesRepository extends \Doctrine\ORM\EntityRepository
{
}
