<?php

namespace AnomaliesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends EntityRepository
{
     public function getRecord($id)
    {
        return $this->createQueryBuilder('d')
                    ->where('d.id = :id')
                    ->setParameter('id', $id)
                    ->getQuery()->getOneOrNullResult();
    }
}
