<?php

namespace AnomaliesBundle\Entity;

/**
 * TypetachesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypetachesRepository extends \Doctrine\ORM\EntityRepository
{
}
