<?php

namespace AnomaliesBundle\Entity;

/**
 * TypesocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
