<?php

namespace AnomaliesBundle\Entity;

/**
 * TypecontroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecontroleRepository extends \Doctrine\ORM\EntityRepository
{
}
