<?php

namespace AnomaliesBundle\Entity;

/**
 * TypecontroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecontroleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEnabledRecords()
    {
        return $this->createQueryBuilder('t')
                    ->where('t.enabled = :enabled')
                    ->setParameter('enabled', '1')
                    ->orderBy('t.typecontrole', 'ASC');
    }
}
