<?php

namespace AnomaliesBundle\Entity;

/**
 * TypesocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesocieteRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getEnabledRecords()
    {
        return $this->createQueryBuilder('t')
                    ->where('t.enabled = :enabled')
                    ->setParameter('enabled', '1')
                    ->orderBy('t.typesociete', 'ASC');
    }
}
